/**
 * Writes `corpus/report.md` — the corpus in a form a person can read.
 *
 * The artifact itself is ~800 KB of JSON and tells you nothing at a glance. The
 * useful questions are which slots the parser reaches, *which exact phrasings*
 * defeat it, and what a failing case actually looks like. This answers those.
 *
 * It runs as a test so it can use the real `parse`, and it writes a committed
 * file on purpose: parser quality then shows up in a diff. A pull request that
 * moves recall says so in the review, instead of hiding inside a log nobody
 * scrolled back to.
 */
import { writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { type CorpusCase, scoreCase, summarize } from './corpus.ts';
import { CORPUS } from './corpus.ts';
import { UNITS } from './grammar.ts';
import { parse } from './parse.ts';
import type { VariableKey } from '../engine/index.ts';
import artifact from '../../corpus/synthetic.json';

interface RawCase {
  id: string;
  text: string;
  expected: Record<string, [number, string]>;
  absent: string[];
  distractors: number[];
  tags: Record<string, unknown>;
  templates: Record<string, string>;
}

const raws = artifact.cases as unknown as RawCase[];

function toCase(raw: RawCase): CorpusCase {
  const expected: CorpusCase['expected'] = {};
  for (const [key, [value, unitName]] of Object.entries(raw.expected)) {
    expected[key as VariableKey] = [value, UNITS[unitName]!];
  }
  return {
    id: raw.id,
    text: raw.text,
    expected,
    absent: raw.absent as VariableKey[],
    distractors: raw.distractors,
    probes: '',
  };
}

const pct = (got: number, total: number) =>
  total === 0 ? '—' : `${Math.round((100 * got) / total)}%`;

/** Which slot a template is responsible for supplying. */
const SLOT_OF: Record<string, VariableKey> = {
  release: 'v0',
  height: 'x1',
  landing: 'x2',
  time: 't',
  speed: 'v',
};

describe('corpus report', () => {
  it('writes corpus/report.md', () => {
    const scores = raws.map((raw) => scoreCase(toCase(raw), parse(raw.text).assignments));
    const totals = summarize(scores);

    // Per slot.
    const perSlot = new Map<string, { got: number; total: number }>();
    const bump = (k: string, hit: boolean) => {
      const e = perSlot.get(k) ?? { got: 0, total: 0 };
      perSlot.set(k, { got: e.got + (hit ? 1 : 0), total: e.total + 1 });
    };
    for (const s of scores) {
      for (const k of s.recovered) bump(k, true);
      for (const k of [...s.missed, ...s.wrong]) bump(k, false);
    }

    // Per phrasing: a template counts as reached when the slot it is
    // responsible for was recovered in that case.
    const perTemplate = new Map<string, { got: number; total: number; kind: string }>();
    raws.forEach((raw, i) => {
      const score = scores[i]!;
      const recovered = new Set(score.recovered);
      for (const [kind, tpl] of Object.entries(raw.templates ?? {})) {
        const slot = SLOT_OF[kind];
        if (!slot || !(slot in raw.expected)) continue;
        const e = perTemplate.get(tpl) ?? { got: 0, total: 0, kind };
        perTemplate.set(tpl, {
          kind,
          got: e.got + (recovered.has(slot) ? 1 : 0),
          total: e.total + 1,
        });
      }
    });

    const templates = [...perTemplate.entries()].sort(
      (a, b) => a[1].got / a[1].total - b[1].got / b[1].total,
    );
    const dead = templates.filter(([, v]) => v.got === 0);

    const wildScores = CORPUS.map((c) => scoreCase(c, parse(c.text).assignments));
    const wild = summarize(wildScores);

    const lines: string[] = [
      '# Corpus report',
      '',
      '> Generated by `npm run corpus:report`. Committed on purpose — parser',
      '> quality then shows up in a diff rather than in a log nobody re-reads.',
      '',
      '## Headline',
      '',
      '| set | cases | slots recovered | recall | wrong | distractors adopted |',
      '| --- | ---: | ---: | ---: | ---: | ---: |',
      `| synthetic | ${raws.length} | ${totals.recovered}/${totals.labeled} | ${pct(totals.recovered, totals.labeled)} | ${totals.wrong} | ${totals.adoptedDistractors} |`,
      `| hand-written | ${CORPUS.length} | ${wild.recovered}/${wild.labeled} | ${pct(wild.recovered, wild.labeled)} | ${wild.wrong} | ${wild.adoptedDistractors} |`,
      '',
      'Never average these. Synthetic measures breadth of phrasing; hand-written',
      'measures reality. A thousand machine-made sentences would drown out the',
      'handful that were actually observed.',
      '',
      '## By slot',
      '',
      '| slot | recovered | recall |',
      '| --- | ---: | ---: |',
      ...[...perSlot.entries()]
        .sort()
        .map(([k, v]) => `| \`${k}\` | ${v.got}/${v.total} | ${pct(v.got, v.total)} |`),
      '',
      '`a` sits at 0% by design: the grammar never emits acceleration, the app',
      'supplies it as a default input. It is counted because the story does imply',
      'it, and hiding it would flatter the number.',
      '',
      `## Phrasings the parser never reaches (${dead.length} of ${templates.length})`,
      '',
      'Each of these appears in the corpus and is recognised in **no** case. This',
      'is the actionable list — every line is a grammar rule that does not exist.',
      '',
      '| slot | phrasing | cases |',
      '| --- | --- | ---: |',
      ...dead.map(([tpl, v]) => `| \`${SLOT_OF[v.kind]}\` | ${tpl} | ${v.total} |`),
      '',
      '## Partially reached',
      '',
      '| slot | phrasing | hit | rate |',
      '| --- | --- | ---: | ---: |',
      ...templates
        .filter(([, v]) => v.got > 0 && v.got < v.total)
        .map(
          ([tpl, v]) =>
            `| \`${SLOT_OF[v.kind]}\` | ${tpl} | ${v.got}/${v.total} | ${pct(v.got, v.total)} |`,
        ),
      '',
      '## Sample failures',
      '',
    ];

    for (const [i, score] of scores.entries()) {
      if (score.missed.length === 0 && score.wrong.length === 0) continue;
      if (lines.filter((l) => l.startsWith('- **')).length >= 8) break;
      const raw = raws[i]!;
      lines.push(
        `- **${raw.id}** — missed \`${score.missed.join('`, `') || '—'}\`` +
          (score.wrong.length ? `, wrong \`${score.wrong.join('`, `')}\`` : '') +
          `\n  > ${raw.text}`,
      );
    }

    lines.push('');
    writeFileSync('corpus/report.md', `${lines.join('\n')}\n`);
    expect(dead.length).toBeLessThanOrEqual(templates.length);
  });
});
